export SUPABASE_URL="https://rtbtwxciigogonbmdqat.supabase.co"
export SUPABASE_SERVICE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0YnR3eGNpaWdvZ29uYm1kcWF0Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4MTg1MjY4MSwiZXhwIjoyMDk3NDI4NjgxfQ.ZuR8ZJILXmk3d9_gLpI8uCrzRLcaK2ByNdMxmvkfEUY"
python scripts/update_breadth.py